#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Created on 2018-03-16 15:41:52
# Project: vander

from pyspider.libs.base_handler import *


class Handler(BaseHandler):
    crawl_config = {
    }
    def __init__(self):
        self.base_url='https://www.vanward.com/pcz3auw5l-'
        self.page_num=1
        self.total_num=5
    @every(minutes=24 * 60)
    def on_start(self):
        while self.page_num <= self.total_num:
            url=self.base_url+str(self.page_num)+'.html'
            print (url)
            self.crawl(url, callback=self.index_page)
            self.page_num +=1     
  
    @config(age=10 * 24 * 60 * 60)
    def index_page(self, response):
        for each in response.doc('a[href^="https://www.vanward.com/pcz3auw5l"]').items():
            self.crawl(each.attr.href, callback=self.detail_page)

    @config(priority=2)
    def detail_page(self, response):
        return {
            #"url": response.url,
            "title": response.doc('title').text(),
            #"conncet1":response.doc('.show_news_con').text(),
            #"conncet2":response.doc('.MsoNormal').text(),
            "conncet3":response.doc('.show_news_con').html(),
           
            
        }
